title: Reeeeeddddd
description: "A bold, unapologetically red Jekyll starter theme made for fun, learning, and showing off."
author: Jaytirth Joshi
encoding: utf-8

exclude: ["README.md", "LICENSE", "*.gem", "*.gemspec", "Gemfile.lock"]